name: movieapp
description: A manager to movies collection.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  # https://docs.flutter.dev/development/accessibility-and-localization/internationalization
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0 
  dio:
  # Animation of a lottie file: https://lottiefiles.com/ 
  lottie:
  # Cache for the images
  cached_network_image:
  # Store the preferences and for while de API response
  shared_preferences:
  # Facilitates the try/catch 
  dartz:
  # Dependence Injection Service Locator
  get_it:
  desktop_window: ^0.4.0
  bitsdojo_window: ^0.1.2
  # Future Dependences:
  # tmdb_api: ^2.1.2
  # flutter_bloc: ^8.0.1
  # equatable: ^2.0.3
  # flutter_modular: ^5.0.2
  # Organize translations, package from dart https://pub.dev/packages/intl_translation
  # flutter pub add intl_translation
  # To control min and max sizes in screen
  # https://pub.dev/packages/bitsdojo_window/
  # flutter pub add bitsdojo_window

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  # Localizations
  generate: true

  assets:
    - assets/

  fonts:
  - family: GoogleSans
    fonts:
    - asset: fonts/GoogleSans-Regular.ttf
  - family: Poppins
    fonts:
    - asset: fonts/Poppins-Regular.ttf
  - family: Raleway
    fonts:
    - asset: fonts/Raleway-Regular.ttf